/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankDetails {
  'ifscCode' : string,
  'accountHolderName' : string,
  'bankName' : string,
  'upiId' : string,
  'accountNumber' : string,
  'uroPayApiKey' : string,
}
export type CurrentStatus = { 'Studying' : null } |
  { 'Working' : null } |
  { 'Other' : null };
export interface CurriculumFeedback {
  'q1' : LikertCurriculum,
  'q2' : LikertCurriculum,
  'q3' : LikertCurriculum,
  'q4' : LikertCurriculum,
  'q5' : LikertCurriculum,
  'q6' : LikertCurriculum,
  'q7' : LikertCurriculum,
  'q8' : LikertCurriculum,
  'suggestions' : string,
}
export type DegreeType = { 'PG' : null } |
  { 'UG' : null } |
  { 'MPhil' : null };
export interface IqacRow {
  'matchingFeedbackExcerpts' : Array<string>,
  'submissionId' : SubmissionId,
  'weaknessText' : string,
  'actionTaken' : string,
  'rowId' : IqacRowId,
}
export type IqacRowId = bigint;
export interface IqacRowInput {
  'matchingFeedbackExcerpts' : Array<string>,
  'weaknessText' : string,
  'actionTaken' : string,
}
export type LikertCurriculum = { 'VeryGood' : null } |
  { 'Satisfactory' : null } |
  { 'Good' : null } |
  { 'Excellent' : null } |
  { 'Unsatisfactory' : null };
export type LikertTeaching = { 'unSatisfactory' : null } |
  { 'veryGood' : null } |
  { 'good' : null } |
  { 'satisfactory' : null } |
  { 'excellent' : null };
export interface Registration {
  'occupation' : [] | [string],
  'name' : string,
  'designation' : [] | [string],
  'collegeAddress' : [] | [string],
  'graduationYear' : bigint,
  'email' : string,
  'company' : [] | [string],
  'collegeIdCard' : [] | [string],
  'companyIdCard' : [] | [string],
  'degreeType' : DegreeType,
  'phone' : string,
  'department' : string,
  'companyAddress' : [] | [string],
  'currentStatus' : CurrentStatus,
  'college' : [] | [string],
  'program' : [] | [string],
  'appointmentOrder' : [] | [string],
}
export interface Submission {
  'curriculum' : CurriculumFeedback,
  'registration' : Registration,
  'submittedAt' : Timestamp,
  'teaching' : TeachingFeedback,
  'contributionAmount' : [] | [bigint],
  'submissionId' : SubmissionId,
}
export type SubmissionId = bigint;
export interface SubmissionSummary {
  'name' : string,
  'submittedAt' : Timestamp,
  'graduationYear' : bigint,
  'email' : string,
  'degreeType' : DegreeType,
  'submissionId' : SubmissionId,
  'department' : string,
}
export interface SubmitFormInput {
  'curriculum' : CurriculumFeedback,
  'registration' : Registration,
  'teaching' : TeachingFeedback,
  'contributionAmount' : [] | [bigint],
}
export interface TeachingFeedback {
  'q1' : LikertTeaching,
  'q2' : LikertTeaching,
  'q3' : LikertTeaching,
  'q4' : LikertTeaching,
  'q5' : LikertTeaching,
  'q6' : LikertTeaching,
  'q7' : LikertTeaching,
  'q8' : LikertTeaching,
  'q9' : LikertTeaching,
  'q10' : LikertTeaching,
  'additionalComments' : string,
  'additionalFacilities' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateActionTakenInput {
  'submissionId' : SubmissionId,
  'actionTaken' : string,
  'rowId' : IqacRowId,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'analyzeSubmission' : ActorMethod<[SubmissionId], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'exportCsv' : ActorMethod<[], string>,
  'getBankDetails' : ActorMethod<[], [] | [BankDetails]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGeminiApiKey' : ActorMethod<[], string>,
  'getIqacRows' : ActorMethod<[SubmissionId], Array<IqacRow>>,
  'getSubmission' : ActorMethod<[SubmissionId], [] | [Submission]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSubmissions' : ActorMethod<[], Array<SubmissionSummary>>,
  'saveIqacRows' : ActorMethod<[SubmissionId, Array<IqacRowInput>], undefined>,
  'setBankDetails' : ActorMethod<[BankDetails], undefined>,
  'setGeminiApiKey' : ActorMethod<[string], undefined>,
  'submitForm' : ActorMethod<[SubmitFormInput], SubmissionId>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateActionTaken' : ActorMethod<[UpdateActionTakenInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];