/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BankDetails = IDL.Record({
  'ifscCode' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'upiId' : IDL.Text,
  'accountNumber' : IDL.Text,
  'uroPayApiKey' : IDL.Text,
});
export const IqacRowId = IDL.Nat;
export const IqacRow = IDL.Record({
  'matchingFeedbackExcerpts' : IDL.Vec(IDL.Text),
  'submissionId' : SubmissionId,
  'weaknessText' : IDL.Text,
  'actionTaken' : IDL.Text,
  'rowId' : IqacRowId,
});
export const LikertCurriculum = IDL.Variant({
  'VeryGood' : IDL.Null,
  'Satisfactory' : IDL.Null,
  'Good' : IDL.Null,
  'Excellent' : IDL.Null,
  'Unsatisfactory' : IDL.Null,
});
export const CurriculumFeedback = IDL.Record({
  'q1' : LikertCurriculum,
  'q2' : LikertCurriculum,
  'q3' : LikertCurriculum,
  'q4' : LikertCurriculum,
  'q5' : LikertCurriculum,
  'q6' : LikertCurriculum,
  'q7' : LikertCurriculum,
  'q8' : LikertCurriculum,
  'suggestions' : IDL.Text,
});
export const DegreeType = IDL.Variant({
  'PG' : IDL.Null,
  'UG' : IDL.Null,
  'MPhil' : IDL.Null,
});
export const CurrentStatus = IDL.Variant({
  'Studying' : IDL.Null,
  'Working' : IDL.Null,
  'Other' : IDL.Null,
});
export const Registration = IDL.Record({
  'occupation' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'designation' : IDL.Opt(IDL.Text),
  'collegeAddress' : IDL.Opt(IDL.Text),
  'graduationYear' : IDL.Nat,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'collegeIdCard' : IDL.Opt(IDL.Text),
  'companyIdCard' : IDL.Opt(IDL.Text),
  'degreeType' : DegreeType,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'companyAddress' : IDL.Opt(IDL.Text),
  'currentStatus' : CurrentStatus,
  'college' : IDL.Opt(IDL.Text),
  'program' : IDL.Opt(IDL.Text),
  'appointmentOrder' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Int;
export const LikertTeaching = IDL.Variant({
  'unSatisfactory' : IDL.Null,
  'veryGood' : IDL.Null,
  'good' : IDL.Null,
  'satisfactory' : IDL.Null,
  'excellent' : IDL.Null,
});
export const TeachingFeedback = IDL.Record({
  'q1' : LikertTeaching,
  'q2' : LikertTeaching,
  'q3' : LikertTeaching,
  'q4' : LikertTeaching,
  'q5' : LikertTeaching,
  'q6' : LikertTeaching,
  'q7' : LikertTeaching,
  'q8' : LikertTeaching,
  'q9' : LikertTeaching,
  'q10' : LikertTeaching,
  'additionalComments' : IDL.Text,
  'additionalFacilities' : IDL.Text,
});
export const Submission = IDL.Record({
  'curriculum' : CurriculumFeedback,
  'registration' : Registration,
  'submittedAt' : Timestamp,
  'teaching' : TeachingFeedback,
  'contributionAmount' : IDL.Opt(IDL.Nat),
  'submissionId' : SubmissionId,
});
export const SubmissionSummary = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'graduationYear' : IDL.Nat,
  'email' : IDL.Text,
  'degreeType' : DegreeType,
  'submissionId' : SubmissionId,
  'department' : IDL.Text,
});
export const IqacRowInput = IDL.Record({
  'matchingFeedbackExcerpts' : IDL.Vec(IDL.Text),
  'weaknessText' : IDL.Text,
  'actionTaken' : IDL.Text,
});
export const SubmitFormInput = IDL.Record({
  'curriculum' : CurriculumFeedback,
  'registration' : Registration,
  'teaching' : TeachingFeedback,
  'contributionAmount' : IDL.Opt(IDL.Nat),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateActionTakenInput = IDL.Record({
  'submissionId' : SubmissionId,
  'actionTaken' : IDL.Text,
  'rowId' : IqacRowId,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'analyzeSubmission' : IDL.Func([SubmissionId], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'exportCsv' : IDL.Func([], [IDL.Text], ['query']),
  'getBankDetails' : IDL.Func([], [IDL.Opt(BankDetails)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGeminiApiKey' : IDL.Func([], [IDL.Text], ['query']),
  'getIqacRows' : IDL.Func([SubmissionId], [IDL.Vec(IqacRow)], ['query']),
  'getSubmission' : IDL.Func([SubmissionId], [IDL.Opt(Submission)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSubmissions' : IDL.Func([], [IDL.Vec(SubmissionSummary)], ['query']),
  'saveIqacRows' : IDL.Func([SubmissionId, IDL.Vec(IqacRowInput)], [], []),
  'setBankDetails' : IDL.Func([BankDetails], [], []),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
  'submitForm' : IDL.Func([SubmitFormInput], [SubmissionId], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateActionTaken' : IDL.Func([UpdateActionTakenInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BankDetails = IDL.Record({
    'ifscCode' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'upiId' : IDL.Text,
    'accountNumber' : IDL.Text,
    'uroPayApiKey' : IDL.Text,
  });
  const IqacRowId = IDL.Nat;
  const IqacRow = IDL.Record({
    'matchingFeedbackExcerpts' : IDL.Vec(IDL.Text),
    'submissionId' : SubmissionId,
    'weaknessText' : IDL.Text,
    'actionTaken' : IDL.Text,
    'rowId' : IqacRowId,
  });
  const LikertCurriculum = IDL.Variant({
    'VeryGood' : IDL.Null,
    'Satisfactory' : IDL.Null,
    'Good' : IDL.Null,
    'Excellent' : IDL.Null,
    'Unsatisfactory' : IDL.Null,
  });
  const CurriculumFeedback = IDL.Record({
    'q1' : LikertCurriculum,
    'q2' : LikertCurriculum,
    'q3' : LikertCurriculum,
    'q4' : LikertCurriculum,
    'q5' : LikertCurriculum,
    'q6' : LikertCurriculum,
    'q7' : LikertCurriculum,
    'q8' : LikertCurriculum,
    'suggestions' : IDL.Text,
  });
  const DegreeType = IDL.Variant({
    'PG' : IDL.Null,
    'UG' : IDL.Null,
    'MPhil' : IDL.Null,
  });
  const CurrentStatus = IDL.Variant({
    'Studying' : IDL.Null,
    'Working' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Registration = IDL.Record({
    'occupation' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'designation' : IDL.Opt(IDL.Text),
    'collegeAddress' : IDL.Opt(IDL.Text),
    'graduationYear' : IDL.Nat,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'collegeIdCard' : IDL.Opt(IDL.Text),
    'companyIdCard' : IDL.Opt(IDL.Text),
    'degreeType' : DegreeType,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'companyAddress' : IDL.Opt(IDL.Text),
    'currentStatus' : CurrentStatus,
    'college' : IDL.Opt(IDL.Text),
    'program' : IDL.Opt(IDL.Text),
    'appointmentOrder' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const LikertTeaching = IDL.Variant({
    'unSatisfactory' : IDL.Null,
    'veryGood' : IDL.Null,
    'good' : IDL.Null,
    'satisfactory' : IDL.Null,
    'excellent' : IDL.Null,
  });
  const TeachingFeedback = IDL.Record({
    'q1' : LikertTeaching,
    'q2' : LikertTeaching,
    'q3' : LikertTeaching,
    'q4' : LikertTeaching,
    'q5' : LikertTeaching,
    'q6' : LikertTeaching,
    'q7' : LikertTeaching,
    'q8' : LikertTeaching,
    'q9' : LikertTeaching,
    'q10' : LikertTeaching,
    'additionalComments' : IDL.Text,
    'additionalFacilities' : IDL.Text,
  });
  const Submission = IDL.Record({
    'curriculum' : CurriculumFeedback,
    'registration' : Registration,
    'submittedAt' : Timestamp,
    'teaching' : TeachingFeedback,
    'contributionAmount' : IDL.Opt(IDL.Nat),
    'submissionId' : SubmissionId,
  });
  const SubmissionSummary = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'graduationYear' : IDL.Nat,
    'email' : IDL.Text,
    'degreeType' : DegreeType,
    'submissionId' : SubmissionId,
    'department' : IDL.Text,
  });
  const IqacRowInput = IDL.Record({
    'matchingFeedbackExcerpts' : IDL.Vec(IDL.Text),
    'weaknessText' : IDL.Text,
    'actionTaken' : IDL.Text,
  });
  const SubmitFormInput = IDL.Record({
    'curriculum' : CurriculumFeedback,
    'registration' : Registration,
    'teaching' : TeachingFeedback,
    'contributionAmount' : IDL.Opt(IDL.Nat),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateActionTakenInput = IDL.Record({
    'submissionId' : SubmissionId,
    'actionTaken' : IDL.Text,
    'rowId' : IqacRowId,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'analyzeSubmission' : IDL.Func([SubmissionId], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'exportCsv' : IDL.Func([], [IDL.Text], ['query']),
    'getBankDetails' : IDL.Func([], [IDL.Opt(BankDetails)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGeminiApiKey' : IDL.Func([], [IDL.Text], ['query']),
    'getIqacRows' : IDL.Func([SubmissionId], [IDL.Vec(IqacRow)], ['query']),
    'getSubmission' : IDL.Func(
        [SubmissionId],
        [IDL.Opt(Submission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSubmissions' : IDL.Func([], [IDL.Vec(SubmissionSummary)], ['query']),
    'saveIqacRows' : IDL.Func([SubmissionId, IDL.Vec(IqacRowInput)], [], []),
    'setBankDetails' : IDL.Func([BankDetails], [], []),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
    'submitForm' : IDL.Func([SubmitFormInput], [SubmissionId], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateActionTaken' : IDL.Func([UpdateActionTakenInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };