/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Registration {
    occupation?: string;
    name: string;
    designation?: string;
    collegeAddress?: string;
    graduationYear: bigint;
    email: string;
    company?: string;
    collegeIdCard?: string;
    companyIdCard?: string;
    degreeType: DegreeType;
    phone: string;
    department: string;
    companyAddress?: string;
    currentStatus: CurrentStatus;
    college?: string;
    program?: string;
    appointmentOrder?: string;
}
export interface IqacRowInput {
    matchingFeedbackExcerpts: Array<string>;
    weaknessText: string;
    actionTaken: string;
}
export interface SubmissionSummary {
    name: string;
    submittedAt: Timestamp;
    graduationYear: bigint;
    email: string;
    degreeType: DegreeType;
    submissionId: SubmissionId;
    department: string;
}
export interface http_header {
    value: string;
    name: string;
}
export type SubmissionId = bigint;
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SubmitFormInput {
    curriculum: CurriculumFeedback;
    registration: Registration;
    teaching: TeachingFeedback;
    contributionAmount?: bigint;
}
export interface BankDetails {
    ifscCode: string;
    accountHolderName: string;
    bankName: string;
    upiId: string;
    accountNumber: string;
    uroPayApiKey: string;
}
export interface IqacRow {
    matchingFeedbackExcerpts: Array<string>;
    submissionId: SubmissionId;
    weaknessText: string;
    actionTaken: string;
    rowId: IqacRowId;
}
export interface CurriculumFeedback {
    q1: LikertCurriculum;
    q2: LikertCurriculum;
    q3: LikertCurriculum;
    q4: LikertCurriculum;
    q5: LikertCurriculum;
    q6: LikertCurriculum;
    q7: LikertCurriculum;
    q8: LikertCurriculum;
    suggestions: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UpdateActionTakenInput {
    submissionId: SubmissionId;
    actionTaken: string;
    rowId: IqacRowId;
}
export interface TeachingFeedback {
    q1: LikertTeaching;
    q2: LikertTeaching;
    q3: LikertTeaching;
    q4: LikertTeaching;
    q5: LikertTeaching;
    q6: LikertTeaching;
    q7: LikertTeaching;
    q8: LikertTeaching;
    q9: LikertTeaching;
    q10: LikertTeaching;
    additionalComments: string;
    additionalFacilities: string;
}
export type IqacRowId = bigint;
export interface Submission {
    curriculum: CurriculumFeedback;
    registration: Registration;
    submittedAt: Timestamp;
    teaching: TeachingFeedback;
    contributionAmount?: bigint;
    submissionId: SubmissionId;
}
export enum CurrentStatus {
    Studying = "Studying",
    Working = "Working",
    Other = "Other"
}
export enum DegreeType {
    PG = "PG",
    UG = "UG",
    MPhil = "MPhil"
}
export enum LikertCurriculum {
    VeryGood = "VeryGood",
    Satisfactory = "Satisfactory",
    Good = "Good",
    Excellent = "Excellent",
    Unsatisfactory = "Unsatisfactory"
}
export enum LikertTeaching {
    unSatisfactory = "unSatisfactory",
    veryGood = "veryGood",
    good = "good",
    satisfactory = "satisfactory",
    excellent = "excellent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    analyzeSubmission(submissionId: SubmissionId): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    exportCsv(): Promise<string>;
    getBankDetails(): Promise<BankDetails | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGeminiApiKey(): Promise<string>;
    getIqacRows(submissionId: SubmissionId): Promise<Array<IqacRow>>;
    getSubmission(id: SubmissionId): Promise<Submission | null>;
    isCallerAdmin(): Promise<boolean>;
    listSubmissions(): Promise<Array<SubmissionSummary>>;
    saveIqacRows(submissionId: SubmissionId, rows: Array<IqacRowInput>): Promise<void>;
    setBankDetails(details: BankDetails): Promise<void>;
    setGeminiApiKey(key: string): Promise<void>;
    submitForm(input: SubmitFormInput): Promise<SubmissionId>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateActionTaken(input: UpdateActionTakenInput): Promise<void>;
}
import type { BankDetails as _BankDetails, CurrentStatus as _CurrentStatus, CurriculumFeedback as _CurriculumFeedback, DegreeType as _DegreeType, LikertCurriculum as _LikertCurriculum, LikertTeaching as _LikertTeaching, Registration as _Registration, Submission as _Submission, SubmissionId as _SubmissionId, SubmissionSummary as _SubmissionSummary, SubmitFormInput as _SubmitFormInput, TeachingFeedback as _TeachingFeedback, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async analyzeSubmission(arg0: SubmissionId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeSubmission(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async exportCsv(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportCsv();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportCsv();
            return result;
        }
    }
    async getBankDetails(): Promise<BankDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankDetails();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankDetails();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGeminiApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGeminiApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGeminiApiKey();
            return result;
        }
    }
    async getIqacRows(arg0: SubmissionId): Promise<Array<IqacRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIqacRows(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIqacRows(arg0);
            return result;
        }
    }
    async getSubmission(arg0: SubmissionId): Promise<Submission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listSubmissions(): Promise<Array<SubmissionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissions();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissions();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveIqacRows(arg0: SubmissionId, arg1: Array<IqacRowInput>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIqacRows(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIqacRows(arg0, arg1);
            return result;
        }
    }
    async setBankDetails(arg0: BankDetails): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBankDetails(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBankDetails(arg0);
            return result;
        }
    }
    async setGeminiApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGeminiApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGeminiApiKey(arg0);
            return result;
        }
    }
    async submitForm(arg0: SubmitFormInput): Promise<SubmissionId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitForm(to_candid_SubmitFormInput_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitForm(to_candid_SubmitFormInput_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateActionTaken(arg0: UpdateActionTakenInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActionTaken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActionTaken(arg0);
            return result;
        }
    }
}
function from_candid_CurrentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurrentStatus): CurrentStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CurriculumFeedback_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurriculumFeedback): CurriculumFeedback {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_DegreeType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DegreeType): DegreeType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_LikertCurriculum_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LikertCurriculum): LikertCurriculum {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_LikertTeaching_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LikertTeaching): LikertTeaching {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Registration_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Registration): Registration {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionSummary_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionSummary): SubmissionSummary {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TeachingFeedback_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeachingFeedback): TeachingFeedback {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BankDetails]): BankDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Submission]): Submission | null {
    return value.length === 0 ? null : from_candid_Submission_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    q1: _LikertCurriculum;
    q2: _LikertCurriculum;
    q3: _LikertCurriculum;
    q4: _LikertCurriculum;
    q5: _LikertCurriculum;
    q6: _LikertCurriculum;
    q7: _LikertCurriculum;
    q8: _LikertCurriculum;
    suggestions: string;
}): {
    q1: LikertCurriculum;
    q2: LikertCurriculum;
    q3: LikertCurriculum;
    q4: LikertCurriculum;
    q5: LikertCurriculum;
    q6: LikertCurriculum;
    q7: LikertCurriculum;
    q8: LikertCurriculum;
    suggestions: string;
} {
    return {
        q1: from_candid_LikertCurriculum_n11(_uploadFile, _downloadFile, value.q1),
        q2: from_candid_LikertCurriculum_n11(_uploadFile, _downloadFile, value.q2),
        q3: from_candid_LikertCurriculum_n11(_uploadFile, _downloadFile, value.q3),
        q4: from_candid_LikertCurriculum_n11(_uploadFile, _downloadFile, value.q4),
        q5: from_candid_LikertCurriculum_n11(_uploadFile, _downloadFile, value.q5),
        q6: from_candid_LikertCurriculum_n11(_uploadFile, _downloadFile, value.q6),
        q7: from_candid_LikertCurriculum_n11(_uploadFile, _downloadFile, value.q7),
        q8: from_candid_LikertCurriculum_n11(_uploadFile, _downloadFile, value.q8),
        suggestions: value.suggestions
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupation: [] | [string];
    name: string;
    designation: [] | [string];
    collegeAddress: [] | [string];
    graduationYear: bigint;
    email: string;
    company: [] | [string];
    collegeIdCard: [] | [string];
    companyIdCard: [] | [string];
    degreeType: _DegreeType;
    phone: string;
    department: string;
    companyAddress: [] | [string];
    currentStatus: _CurrentStatus;
    college: [] | [string];
    program: [] | [string];
    appointmentOrder: [] | [string];
}): {
    occupation?: string;
    name: string;
    designation?: string;
    collegeAddress?: string;
    graduationYear: bigint;
    email: string;
    company?: string;
    collegeIdCard?: string;
    companyIdCard?: string;
    degreeType: DegreeType;
    phone: string;
    department: string;
    companyAddress?: string;
    currentStatus: CurrentStatus;
    college?: string;
    program?: string;
    appointmentOrder?: string;
} {
    return {
        occupation: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.occupation)),
        name: value.name,
        designation: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.designation)),
        collegeAddress: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.collegeAddress)),
        graduationYear: value.graduationYear,
        email: value.email,
        company: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.company)),
        collegeIdCard: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.collegeIdCard)),
        companyIdCard: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.companyIdCard)),
        degreeType: from_candid_DegreeType_n16(_uploadFile, _downloadFile, value.degreeType),
        phone: value.phone,
        department: value.department,
        companyAddress: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.companyAddress)),
        currentStatus: from_candid_CurrentStatus_n18(_uploadFile, _downloadFile, value.currentStatus),
        college: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.college)),
        program: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.program)),
        appointmentOrder: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.appointmentOrder))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    q1: _LikertTeaching;
    q2: _LikertTeaching;
    q3: _LikertTeaching;
    q4: _LikertTeaching;
    q5: _LikertTeaching;
    q6: _LikertTeaching;
    q7: _LikertTeaching;
    q8: _LikertTeaching;
    q9: _LikertTeaching;
    q10: _LikertTeaching;
    additionalComments: string;
    additionalFacilities: string;
}): {
    q1: LikertTeaching;
    q2: LikertTeaching;
    q3: LikertTeaching;
    q4: LikertTeaching;
    q5: LikertTeaching;
    q6: LikertTeaching;
    q7: LikertTeaching;
    q8: LikertTeaching;
    q9: LikertTeaching;
    q10: LikertTeaching;
    additionalComments: string;
    additionalFacilities: string;
} {
    return {
        q1: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q1),
        q2: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q2),
        q3: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q3),
        q4: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q4),
        q5: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q5),
        q6: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q6),
        q7: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q7),
        q8: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q8),
        q9: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q9),
        q10: from_candid_LikertTeaching_n22(_uploadFile, _downloadFile, value.q10),
        additionalComments: value.additionalComments,
        additionalFacilities: value.additionalFacilities
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    submittedAt: _Timestamp;
    graduationYear: bigint;
    email: string;
    degreeType: _DegreeType;
    submissionId: _SubmissionId;
    department: string;
}): {
    name: string;
    submittedAt: Timestamp;
    graduationYear: bigint;
    email: string;
    degreeType: DegreeType;
    submissionId: SubmissionId;
    department: string;
} {
    return {
        name: value.name,
        submittedAt: value.submittedAt,
        graduationYear: value.graduationYear,
        email: value.email,
        degreeType: from_candid_DegreeType_n16(_uploadFile, _downloadFile, value.degreeType),
        submissionId: value.submissionId,
        department: value.department
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    curriculum: _CurriculumFeedback;
    registration: _Registration;
    submittedAt: _Timestamp;
    teaching: _TeachingFeedback;
    contributionAmount: [] | [bigint];
    submissionId: _SubmissionId;
}): {
    curriculum: CurriculumFeedback;
    registration: Registration;
    submittedAt: Timestamp;
    teaching: TeachingFeedback;
    contributionAmount?: bigint;
    submissionId: SubmissionId;
} {
    return {
        curriculum: from_candid_CurriculumFeedback_n9(_uploadFile, _downloadFile, value.curriculum),
        registration: from_candid_Registration_n13(_uploadFile, _downloadFile, value.registration),
        submittedAt: value.submittedAt,
        teaching: from_candid_TeachingFeedback_n20(_uploadFile, _downloadFile, value.teaching),
        contributionAmount: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.contributionAmount)),
        submissionId: value.submissionId
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VeryGood: null;
} | {
    Satisfactory: null;
} | {
    Good: null;
} | {
    Excellent: null;
} | {
    Unsatisfactory: null;
}): LikertCurriculum {
    return "VeryGood" in value ? LikertCurriculum.VeryGood : "Satisfactory" in value ? LikertCurriculum.Satisfactory : "Good" in value ? LikertCurriculum.Good : "Excellent" in value ? LikertCurriculum.Excellent : "Unsatisfactory" in value ? LikertCurriculum.Unsatisfactory : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PG: null;
} | {
    UG: null;
} | {
    MPhil: null;
}): DegreeType {
    return "PG" in value ? DegreeType.PG : "UG" in value ? DegreeType.UG : "MPhil" in value ? DegreeType.MPhil : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Studying: null;
} | {
    Working: null;
} | {
    Other: null;
}): CurrentStatus {
    return "Studying" in value ? CurrentStatus.Studying : "Working" in value ? CurrentStatus.Working : "Other" in value ? CurrentStatus.Other : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unSatisfactory: null;
} | {
    veryGood: null;
} | {
    good: null;
} | {
    satisfactory: null;
} | {
    excellent: null;
}): LikertTeaching {
    return "unSatisfactory" in value ? LikertTeaching.unSatisfactory : "veryGood" in value ? LikertTeaching.veryGood : "good" in value ? LikertTeaching.good : "satisfactory" in value ? LikertTeaching.satisfactory : "excellent" in value ? LikertTeaching.excellent : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubmissionSummary>): Array<SubmissionSummary> {
    return value.map((x)=>from_candid_SubmissionSummary_n26(_uploadFile, _downloadFile, x));
}
function to_candid_CurrentStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CurrentStatus): _CurrentStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_CurriculumFeedback_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CurriculumFeedback): _CurriculumFeedback {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_DegreeType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DegreeType): _DegreeType {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_LikertCurriculum_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LikertCurriculum): _LikertCurriculum {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_LikertTeaching_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LikertTeaching): _LikertTeaching {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_Registration_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Registration): _Registration {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitFormInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitFormInput): _SubmitFormInput {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_TeachingFeedback_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeachingFeedback): _TeachingFeedback {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    curriculum: CurriculumFeedback;
    registration: Registration;
    teaching: TeachingFeedback;
    contributionAmount?: bigint;
}): {
    curriculum: _CurriculumFeedback;
    registration: _Registration;
    teaching: _TeachingFeedback;
    contributionAmount: [] | [bigint];
} {
    return {
        curriculum: to_candid_CurriculumFeedback_n30(_uploadFile, _downloadFile, value.curriculum),
        registration: to_candid_Registration_n34(_uploadFile, _downloadFile, value.registration),
        teaching: to_candid_TeachingFeedback_n40(_uploadFile, _downloadFile, value.teaching),
        contributionAmount: value.contributionAmount ? candid_some(value.contributionAmount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    q1: LikertCurriculum;
    q2: LikertCurriculum;
    q3: LikertCurriculum;
    q4: LikertCurriculum;
    q5: LikertCurriculum;
    q6: LikertCurriculum;
    q7: LikertCurriculum;
    q8: LikertCurriculum;
    suggestions: string;
}): {
    q1: _LikertCurriculum;
    q2: _LikertCurriculum;
    q3: _LikertCurriculum;
    q4: _LikertCurriculum;
    q5: _LikertCurriculum;
    q6: _LikertCurriculum;
    q7: _LikertCurriculum;
    q8: _LikertCurriculum;
    suggestions: string;
} {
    return {
        q1: to_candid_LikertCurriculum_n32(_uploadFile, _downloadFile, value.q1),
        q2: to_candid_LikertCurriculum_n32(_uploadFile, _downloadFile, value.q2),
        q3: to_candid_LikertCurriculum_n32(_uploadFile, _downloadFile, value.q3),
        q4: to_candid_LikertCurriculum_n32(_uploadFile, _downloadFile, value.q4),
        q5: to_candid_LikertCurriculum_n32(_uploadFile, _downloadFile, value.q5),
        q6: to_candid_LikertCurriculum_n32(_uploadFile, _downloadFile, value.q6),
        q7: to_candid_LikertCurriculum_n32(_uploadFile, _downloadFile, value.q7),
        q8: to_candid_LikertCurriculum_n32(_uploadFile, _downloadFile, value.q8),
        suggestions: value.suggestions
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupation?: string;
    name: string;
    designation?: string;
    collegeAddress?: string;
    graduationYear: bigint;
    email: string;
    company?: string;
    collegeIdCard?: string;
    companyIdCard?: string;
    degreeType: DegreeType;
    phone: string;
    department: string;
    companyAddress?: string;
    currentStatus: CurrentStatus;
    college?: string;
    program?: string;
    appointmentOrder?: string;
}): {
    occupation: [] | [string];
    name: string;
    designation: [] | [string];
    collegeAddress: [] | [string];
    graduationYear: bigint;
    email: string;
    company: [] | [string];
    collegeIdCard: [] | [string];
    companyIdCard: [] | [string];
    degreeType: _DegreeType;
    phone: string;
    department: string;
    companyAddress: [] | [string];
    currentStatus: _CurrentStatus;
    college: [] | [string];
    program: [] | [string];
    appointmentOrder: [] | [string];
} {
    return {
        occupation: value.occupation ? candid_some(value.occupation) : candid_none(),
        name: value.name,
        designation: value.designation ? candid_some(value.designation) : candid_none(),
        collegeAddress: value.collegeAddress ? candid_some(value.collegeAddress) : candid_none(),
        graduationYear: value.graduationYear,
        email: value.email,
        company: value.company ? candid_some(value.company) : candid_none(),
        collegeIdCard: value.collegeIdCard ? candid_some(value.collegeIdCard) : candid_none(),
        companyIdCard: value.companyIdCard ? candid_some(value.companyIdCard) : candid_none(),
        degreeType: to_candid_DegreeType_n36(_uploadFile, _downloadFile, value.degreeType),
        phone: value.phone,
        department: value.department,
        companyAddress: value.companyAddress ? candid_some(value.companyAddress) : candid_none(),
        currentStatus: to_candid_CurrentStatus_n38(_uploadFile, _downloadFile, value.currentStatus),
        college: value.college ? candid_some(value.college) : candid_none(),
        program: value.program ? candid_some(value.program) : candid_none(),
        appointmentOrder: value.appointmentOrder ? candid_some(value.appointmentOrder) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    q1: LikertTeaching;
    q2: LikertTeaching;
    q3: LikertTeaching;
    q4: LikertTeaching;
    q5: LikertTeaching;
    q6: LikertTeaching;
    q7: LikertTeaching;
    q8: LikertTeaching;
    q9: LikertTeaching;
    q10: LikertTeaching;
    additionalComments: string;
    additionalFacilities: string;
}): {
    q1: _LikertTeaching;
    q2: _LikertTeaching;
    q3: _LikertTeaching;
    q4: _LikertTeaching;
    q5: _LikertTeaching;
    q6: _LikertTeaching;
    q7: _LikertTeaching;
    q8: _LikertTeaching;
    q9: _LikertTeaching;
    q10: _LikertTeaching;
    additionalComments: string;
    additionalFacilities: string;
} {
    return {
        q1: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q1),
        q2: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q2),
        q3: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q3),
        q4: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q4),
        q5: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q5),
        q6: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q6),
        q7: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q7),
        q8: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q8),
        q9: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q9),
        q10: to_candid_LikertTeaching_n42(_uploadFile, _downloadFile, value.q10),
        additionalComments: value.additionalComments,
        additionalFacilities: value.additionalFacilities
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LikertCurriculum): {
    VeryGood: null;
} | {
    Satisfactory: null;
} | {
    Good: null;
} | {
    Excellent: null;
} | {
    Unsatisfactory: null;
} {
    return value == LikertCurriculum.VeryGood ? {
        VeryGood: null
    } : value == LikertCurriculum.Satisfactory ? {
        Satisfactory: null
    } : value == LikertCurriculum.Good ? {
        Good: null
    } : value == LikertCurriculum.Excellent ? {
        Excellent: null
    } : value == LikertCurriculum.Unsatisfactory ? {
        Unsatisfactory: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DegreeType): {
    PG: null;
} | {
    UG: null;
} | {
    MPhil: null;
} {
    return value == DegreeType.PG ? {
        PG: null
    } : value == DegreeType.UG ? {
        UG: null
    } : value == DegreeType.MPhil ? {
        MPhil: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CurrentStatus): {
    Studying: null;
} | {
    Working: null;
} | {
    Other: null;
} {
    return value == CurrentStatus.Studying ? {
        Studying: null
    } : value == CurrentStatus.Working ? {
        Working: null
    } : value == CurrentStatus.Other ? {
        Other: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LikertTeaching): {
    unSatisfactory: null;
} | {
    veryGood: null;
} | {
    good: null;
} | {
    satisfactory: null;
} | {
    excellent: null;
} {
    return value == LikertTeaching.unSatisfactory ? {
        unSatisfactory: null
    } : value == LikertTeaching.veryGood ? {
        veryGood: null
    } : value == LikertTeaching.good ? {
        good: null
    } : value == LikertTeaching.satisfactory ? {
        satisfactory: null
    } : value == LikertTeaching.excellent ? {
        excellent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
